# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
localized_homepage:
  url: /:sf_culture
  param: { module: video, action: index }
  requeriments:
    sf_culture: (?:en|es)

homepage:
  url:   /
  param: { module: video, action: index }

author:
  url:   /author/:slug
  class: sfPropelRoute
  param: { module: author, action: show }
  options: { model: Author, type: object}
category:
  url:   /category/:slug
  class: sfPropelRoute
  param: { module: category, action: show }
  options: { model: Category, type: object}
score:
  url:   /score/:slug
  class: sfPropelRoute
  param: { module: score, action: show }
  options: { model: Score, type: object}

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
