<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/19 17:58:21

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=t5v;host=localhost',
  'username' => 't5vuser',
  'password' => 't5vpass',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
