generator:
  class: sfPropelGenerator
  param:
    model_class:           Category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Category
    plural:                Categorys
    route_prefix:          category
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Category Management
      filter:  ~
      form:    ~
      edit:
        title: Editing Category %%name%%
      new:
        title: New Category
