generator:
  class: sfPropelGenerator
  param:
    model_class:           Author
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Author
    plural:                Authors
    route_prefix:          author
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Author Management
      filter:  ~
      form:    ~
      edit:
        title: Editing %%name%%
      new:
        title: New Author
